### ISSUE TITLE
Problem with posts in scandic languages

### ISSUE THREAD

**Issue by andravasile** [minimaxir/facebook-page-post-scraper#3]
Hello!

I am getting this error because I am trying to get the posts from a norwegian fb page... Could you please help me to fix it?

UnicodeEncodeError: 'ascii' codec can't encode character u'\xe5' in position 52: ordinal not in range(128)

I tried to put this comment line at the beginning of my code, but it still does not work.

-- coding: utf-8 --

Thank you in advance!

**Comment by minimaxir** [comment]
Hi, I updated the script with a `unicode_normalize` function which may fix this. Can you see if that works?

**Comment by andravasile** [comment]
Thanks! I do not get any error anymore and the texts are ok if I visualize the cvs file in PyCharm, but I still do not get the good letters if I open it with Microsoft Excel.

**Comment by ankit96** [comment]
Your code is scrapping all the post from the FB page including those which are posted by visitors on that page.If I want only those post which are from the page owner,can you suggest me how to do it,please

**Comment by minimaxir** [comment]
It turns out the fix is to literally change the word /feed to /posts. Programming is fun!

<img width="684" alt="screen shot 2016-05-12 at 10 52 15 pm" src="https://cloud.githubusercontent.com/assets/2179708/15239158/089fcf3e-1895-11e6-8e06-7ee986942989.png">

Issue fixed in https://github.com/minimaxir/facebook-page-post-scraper/commit/da923205e73350f4d0e23bb41c492152104680f6
